name: Release

on:
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Required for creating GitHub release.
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PRODUCT: flameshot

jobs:
  build-windows:
    name: ${{ matrix.config.name }}
    runs-on: "Windows Server 2022 / Qt 6"
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]
        arch: [win64_msvc2019_64]
        platform: [x64]
        qt: [6.7.1]
        qt_modules: [qtwebengine qtwebchannel qtpositioning qtpdf qtimageformats qt5compat]

    steps:
      - name: Get clone
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get cmake 
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg-configuration.json'

      - name: Install Qt Official Build
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{matrix.qt}}
          target: desktop
          arch: ${{matrix.arch}}
          modules: ${{matrix.qt_modules}}
          cache: 'true'

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name:  Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target all_build --
        
      - name:  Install Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

      - name: Zip Package
        run: |
          mkdir -p dist
          Compress-Archive -Path "build/Release/*" -DestinationPath "dist/test.zip"

      - name: Create .msi package
      run: |
        mkdir -p dist
        candle.exe -nologo -out dist/product.wixobj scripts/product.wxs
        light.exe -nologo -out dist/product.msi dist/product.wixobj
      
      - name: Calculate SHA256 checksums for each file
        run: |
          mkdir -p dist/sha256sums
          $Files = Get-ChildItem -File -Path "dist/*"
          foreach ($File in $Files) {
              $Hash = Get-FileHash $File.FullName -Algorithm SHA256
              $HashFile = "dist/sha256sums/$($File.Name).sha256"
              "$($Hash.Hash) *$($File.Name)" | Out-File -FilePath $HashFile
          }

      - name: Update GitHub Release
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            dist/*

